### ISSUE TITLE
open.connection(con, "rb") : HTTP error 429.

### ISSUE THREAD

**Issue by daenuthelawyer** [stevecondylios/priceR#23]
Hello.

After starting up my R session and executing an priceR function, like so
`priceR::currencies()`
I get the following error: 

For full currency exchange rate API documentation visit:
 https://exchangerate.host/#/#docs
 (this message will only appear once per session)
Fehler in open.connection(con, "rb") : HTTP error 429.

One hour ago your package worked flawlessly with me.
Is this a known error or due to my programming/environment?

**Comment by daenuthelawyer** [comment]
Ok, now it works again, without any change by me, maybe the api was hanging.

**Comment by stevecondylios** [comment]
Hi @daenuthelawyer thanks for reporting. 

A 429 http status code is [too many requests](https://httpstatuses.com/429). I'm not privy to the exchange rate host API internals, but I suspect they have some rate limiting in place which may cause a 429 status code to be returned when it receives a lot of requests (perhaps it has a lot of users right now)

One suggestions is to place `Sys.sleep(3)` between requests to slow down the time between requests

**Comment by daenuthelawyer** [comment]
Dear @stevecondylios 
Thanks for your fast response and helpful suggestion.
I will keep that in mind and convert my currencies in lists rather than one by one such as to limit the number of requests.
Best
