### ISSUE TITLE
HTTP Error 521

### ISSUE THREAD

**Issue by tanyanchongDA** [stevecondylios/priceR#26]
Hi,

There seems to have a recent problem with extracting exchange rate information from PriceR. 

`priceR::exchange_rate_latest("USD") %>% 
  head(10)`

It results in Error in open.connection(con, "rb") : HTTP error 521.

May I know if there is an issue with the server?

Thank you very much in advance!

**Comment by stevecondylios** [comment]
Very interesting, I haven't seen a 521 before, looks like the [cloudflare server is down](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_server_errors):

> 521 Web Server Is Down
Error 521 occurs when the origin web server refuses connections from Cloudflare. Security solutions at your origin may block legitimate connections from certain Cloudflare IP addresses.

I see it has been reported upstream: https://github.com/Formicka/exchangerate.host/issues/47

Hopefully it's fixed soon.

**Comment by stevecondylios** [comment]
It was a temporary server outage, fixed in https://github.com/Formicka/exchangerate.host/issues/47#issuecomment-826498691
