### ISSUE TITLE
cannot open URL error

### ISSUE THREAD

**Issue by antoine4ucsd** [stevecondylios/priceR#44]
Hello
I have been using this really nice packages for months but today I got this message:

![Screen Shot 2023-09-22 at 11 03 09 AM](https://github.com/stevecondylios/priceR/assets/18502631/d2ff386e-dd7b-4ab0-aa29-349420e7eca9)

any suggestions?

is there an 'off line' alternative if this issue persists?
thank you!

**Comment by stevecondylios** [comment]
Thanks for letting me know. Looks like many others are experiencing the same as there is a problem with the exchange rates API: 

https://github.com/Formicka/exchangerate.host/issues/236

Hopefully the issue with the API is resolved soon.

**Comment by antoine4ucsd** [comment]
thank you!

**Comment by stevecondylios** [comment]
Based on comments on the related issue, and some testing, it looks like it should be working again now. 

Someone guessed based on an iptrace that the cause could have been a hardware issue: https://github.com/Formicka/exchangerate.host/issues/236#issuecomment-1731955679
